### ISSUE TITLE
GOOGLEWORKSPACE_CREDENTIALS not reading key when `~` is in the path

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-googleworkspace#105]
### Terraform Version
`0.15.3`
`hashicorp/googleworkspace v0.2.0`

### Affected Resource(s)
`GOOGLEWORKSPACE_CREDENTIALS` environment variable.

### Terraform Configuration Files
GCP service account key located at `~/.gcloud/keys/googleworkspace.key` on my filesystem and `GOOGLEWORKSPACE_CREDENTIALS=~/.gcloud/keys/googleworkspace.key` set in the environment

### Expected Behavior
Per https://registry.terraform.io/providers/hashicorp/googleworkspace/latest/docs#creating-a-service-account-and-credentials saying "set the GOOGLEWORKSPACE_CREDENTIALS environment variable to the path of the service account key.", I expected that the provider would read in the key that exists at that file path and use it for authentication.

### Actual Behavior
```
│ Error: JSON credentials in "~/.gcloud/keys/googleworkspace.key" are not valid: invalid character '~' looking for beginning of value
│ 
│   with provider["registry.terraform.io/hashicorp/googleworkspace"],
│   on terraform.tf line 33, in provider "googleworkspace":
│   33: provider "googleworkspace" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Put the service account key at `~/.gcloud/keys/googleworkspace.key`
2. `export GOOGLEWORKSPACE_CREDENTIALS="~/.gcloud/keys/googleworkspace.key"`
3. `terraform plan`

**Comment by appilon** [comment]
Hello, it's my understanding that placing the path in quotes `"~/path/to/creds"` means the homedir shortcut path is not expanded by the OS/shell. We thought we had added expansion in the provider as an extra convenience, I'll take a look at what's going on there, but you should be able to get your environment variable working by unquoting the string, allowing the tilde `~` expansion to take place.
