### ISSUE TITLE
Provider requires `impersonated_user_email` even when not needed

### ISSUE THREAD

**Issue by ericnorris** [hashicorp/terraform-provider-googleworkspace#112]
Thanks for the work so far on this provider!

### Terraform Version
N/A

### Affected Resource(s)
`googleworkspace_group_*`

### Terraform Configuration Files
```hcl
provider "googleworkspace" {
  customer_id = "some-customer-id"
}
```

(`GOOGLE_CREDENTIALS` environment variable is set)

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The provider should work without `impersonated_user_email` when interacting **only** with `googleworkspace_group_*` resources, even if credentials are specified in an environment variable.

### Actual Behavior
Received the following 

https://github.com/hashicorp/terraform-provider-googleworkspace/blob/4a497b1b40707a98eef74aee5f76df5bd5a5c201/internal/provider/provider_config.go#L42

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `GOOGLE_CREDENTIALS=$(cat /path/to/key) terraform plan`

### Important Factoids

I've heard from a PM (and confirmed with local testing) that you do not need to impersonate a user via Domain Wide Delegation when interacting with the Group API, so long as you have `Group Admin` (similar to https://cloud.google.com/identity/docs/how-to/setup#auth-no-dwd, though this is for Cloud Identity). Unfortunately the provider requires that we pass in a `impersonated_user_email` value, even if we're only planning on making `googleworkspace_group_*` resources.

You can test that this works (without impersonating a user) with the following workaround:

```hcl
provider "googleworkspace" {
  customer_id             = "some-customer-id"
  impersonated_user_email = "exact-same-email-address-as-the-service-account-credentials"
}

resource "googleworkspace_group" "test_group" {
  email       = "test-group@example.com"
  name        = "Test Group"

  aliases = []
}
```

### References
N/A

**Comment by appilon** [comment]
Hi @ericnorris, if I am understanding correctly, you are hoping we can make `impersonated_user_email` optional depending on the resources being used in the particular apply. Unfortunately resource management is handled entirely by Terraform Core, and the provider merely provides a mapping of attributes to requests of the API. It won't be possible for the provider to dynamically change the requirements of the provider block, based on the particular resources used at runtime. Your current workaround may be your best bet for now.

We may be able to naively set the `subject` of the oauth request to whatever email is present in the credentials file, should `impersonated_user_email` be unset. This may have the desired effect you are seeking? But there is a chance the google API is unhappy with the oauth request based on the scopes (if left unset, we pass all scopes required by all the resources the provider currently has implemented)? You would likely receive an oauth API error response.

**Comment by ericnorris** [comment]
Hey @appilon, I should have been more clear - I'd like to remove the requirement that `impersonated_user_email` be set, i.e. make it always optional, rather than optional depending on the resources that you use. I'm familiar enough with how `terraform` works to understand why the latter would not be possible.

Setting `impersonated_user_email` implicitly to the value of the service account's email may work; I'd rather have it not sent at all since it's not necessary, but I defer to you all on what the right thing is to do here.

**Comment by ericnorris** [comment]
Thanks @appilon, appreciate the speedy implementation!
