### ISSUE TITLE
googleworkspace_group_settings - Error: timed out while waiting for group settings to be updated

### ISSUE THREAD

**Issue by dwilliams782** [hashicorp/terraform-provider-googleworkspace#114]
### Terraform Version
0.14.7

### Affected Resource(s)
- googleworkspace_group_settings

### Debug Output
https://gist.github.com/dwilliams782/41074546edeeb5a989446d6d122f1d34

### Code
The following is a module:

```hcl
// ----------- Group -----------

resource "googleworkspace_group" "group" {
  description = "Managed by Terraform."
  email       = var.email
  name        = var.name

  aliases = var.aliases

  timeouts {
    create = "1m"
    update = "1m"
  }
}

// ----------- Group Members -----------

resource "googleworkspace_group_member" "user" {
  for_each = var.users != null ? var.users : []
  group_id = googleworkspace_group.group.id
  email    = each.value

  delivery_settings = "DISABLED"
  role              = "MEMBER"
  type              = "USER"

  depends_on = [
    googleworkspace_group.group,
    googleworkspace_group_settings.group-settings
  ]
}

resource "googleworkspace_group_member" "group" {
  for_each = var.groups != null ? var.groups : []
  group_id = googleworkspace_group.group.id
  email    = each.value

  delivery_settings = "DISABLED"
  role              = "MEMBER"
  type              = "GROUP"

  depends_on = [
    googleworkspace_group.group,
    googleworkspace_group_settings.group-settings
  ]
}

// ----------- Group Settings -----------

resource "googleworkspace_group_settings" "group-settings" {
  email = googleworkspace_group.group.email

  allow_external_members         = var.allow_external_members
  allow_web_posting              = var.allow_web_posting
  enable_collaborative_inbox     = var.enable_collaborative_inbox
  include_in_global_address_list = var.include_in_global_address_list
  members_can_post_as_the_group  = var.members_can_post_as_the_group
  who_can_contact_owner          = var.who_can_contact_owner
  who_can_join                   = var.who_can_join
  who_can_leave_group            = var.who_can_leave_group
  who_can_view_membership        = var.who_can_view_membership
  who_can_post_message           = var.who_can_post_message

  depends_on = [googleworkspace_group.group]

  timeouts {
    create = "1m"
    update = "1m"
  }
}

```

### Actual Behavior
This request to create a group settings resource is timing out, but the debug logs are showing 200 OK on each request.

```
Error: timed out while waiting for group settings to be updated

  on modules/_components/iam/google-group/group.tf line 44, in resource "googleworkspace_group_settings" "group-settings":
  44: resource "googleworkspace_group_settings" "group-settings" {

```

This is inconsistent but has been very repeatable for me, and is breaking my use of this provider through our ci/cd systems.

**Comment by dwilliams782** [comment]
I've settled on using `0.2.0` for now with a short timeout - this seems to be more consistent, and when it reaches the end of the timeout it succeeds rather than fails.

**Comment by appilon** [comment]
it appears the resource was failing to check for an error in v0.2.0, this was corrected in v0.3.0 https://github.com/hashicorp/terraform-provider-googleworkspace/compare/v0.2.0...v0.3.0#diff-3988371d60c5aa9d994043cc3e7457543f5632fe80d4fb9ff434b813c44f8c6dR406

I'm looking into trying to achieve better consistency now

**Comment by appilon** [comment]
@dwilliams782 is this happening on create or on update? There was a change between 0.2.0 and 0.3.0, where we forgot to check if there was an error, it could be the timeout issue is always present, just failing silently in 0.2.0

**Comment by dwilliams782** [comment]
Yes, that sounds correct, however the settings are being applied correctly so I'm OK with failing silently for now rather than not being able to use it at all! Thank you.
