### ISSUE TITLE
Error: googleapi: Error 404: Resource Not Found: <id>, notFound

### ISSUE THREAD

**Issue by dwilliams782** [hashicorp/terraform-provider-googleworkspace#132]
Hi,

When a user has been deleted, our entire plan fails due to the group_member resource still being in state:

```
Error: googleapi: Error 404: Resource Not Found: 1040763465893, notFound
```

I understand why, but until these groups are fully adopted into our JML process, this breaks the terraform plan for all other groups / users. It's not easy to identify which user this is, either. 

We have identified the failed user, however the plan still errors due to that user being in state, and it attempts to refresh the resource. This breaks our whole pipeline, for cases where the user is removed prior to the group being updated. We cannot manage users in this same workflow. Is there a way to prevent this? I've had to remove the group member resource from state to fix this.

**Comment by jacobstr** [comment]
Finding this may be quite the thorn to work around as well. It'd be nice to have some notion of authoritative group membership vs non-authoritative ala (google_iam_member vs. google_iam_binding).

**Comment by dwilliams782** [comment]
I've seen similar patterns with SQL related providers before where, if the user doesn't exist, it simply gets removed from state as part of the plan. That would be sufficient for us; the plan would show one to add, which would then fail on apply as the user doesn't exist so can't be added to the group.

**Comment by megan07** [comment]
@jacobstr - Thanks for the quick response! I've got a fix in for this now. Sorry about that!

**Comment by dwilliams782** [comment]
@megan07 Just deployed 0.4.1, instantly fixed our issue, thank you again!
