### ISSUE TITLE
Required scopes for data resource googleworkspace_user

### ISSUE THREAD

**Issue by dwilliams782** [hashicorp/terraform-provider-googleworkspace#134]
Hi, what scopes are required for the data resource `googleworkspace_user`? I've tried:

```
oauth_scopes = [
    "https://www.googleapis.com/auth/admin.directory.group",
    "https://www.googleapis.com/auth/admin.directory.user",
    "https://www.googleapis.com/auth/admin.directory.userschema.readonly",
    "https://www.googleapis.com/auth/apps.groups.settings"
  ]
```

but still get an insufficient scopes error. Thanks!

**Comment by vhatsura** [comment]
@dwilliams782, you need to ask for `https://www.googleapis.com/auth/admin.directory.user.readonly` scope

**Comment by megan07** [comment]
Hi @dwilliams782! I wanted to check in and see if this worked and we can close the issue? Thanks!
