### ISSUE TITLE
googleworkspace_user has a permadiff on default `emails` fields

### ISSUE THREAD

**Issue by ari-becker** [hashicorp/terraform-provider-googleworkspace#150]
### Terraform Version
provider version `0.4.1`

### Affected Resource(s)
`googleworkspace_user`

### Terraform Configuration Files
default `googleworkspace_user`, with minimal fields defined

### Expected Behavior
No permadiff

### Actual Behavior
Permadiff in terraform plan:

```text
      - emails {

          - address = "ari@example.com" -> null

          - primary = true -> null

        }

      - emails {

          - address = "ari@example.com.test-google-a.com" -> null

          - primary = false -> null

        }

      - emails {

          - address = "ari@secondary.example.com" -> null

          - primary = false -> null

        }

```

Running `terraform apply` succeeds, but does not actually delete the email addresses (the provider can't - these are the default addresses that belong to the user), and does not result in future plans no longer including the intention to delete these fields -> a permadiff.

Attempting to get rid of the permadiff by adding the fields manually, i.e.

```text
resource "googleworkspace_user" "example" {
  ...

  emails {
    address = "ari@example.com"
    primary = true
  }

  emails {
    address = "ari@example.com.test-google-a.com"
    primary = false
  }

  emails {
    address = "ari@secondary.example.com"
    primary = false
  }
}
```

Results in the following error message:

```text
│ Error: Missing required argument

│ 

│   on provider_googleworkspace_users.tf line 47, in resource "googleworkspace_user" "example":

│   47:   emails {

│ 

│ The argument "type" is required, but no definition was found.

```

since https://github.com/hashicorp/terraform-provider-googleworkspace/commit/83b8fd3395f885c38aa1fc64516022b58cf21d09 added "type" as a required field. However, it does not seem to be defined in the underlying API for these default fields.

**Comment by megan07** [comment]
Hi @ari-becker! Sorry you're running into this. I'm not certain I fully understand the context of this situation, but I'll try to and you can correct me if I'm wrong.

1) The email addresses being returned are not in your configuration, and cannot be deleted by the API, resulting in a permadiff? I see the `<primary>` and the `<primary>`.`test-google-a.com` are listed there,  how was the `ari@secondary.example.com` added? This is likely the only one that would be able to be removed? If you wouldn't mind providing me with your configuration and steps to reproduce (or debug logs), that'd be great! Thanks!

2) As for your solution, I think the error you're seeing is a Terraform error saying that [`type`](https://registry.terraform.io/providers/hashicorp/googleworkspace/latest/docs/resources/user#nested-schema-for-emails) is not defined in your configuration, but is required. It is an option in the underlying API. It is a little odd, though, that it's required on create, but is not returned by the API - I think it's only for certain email addresses. Specifically speaking, the `<primary>` and the `<primary>`.`test-google-a.com`, they probably don't have an associated type?

As I'm looking at it now, I think there may be an error in the diff suppress function, perhaps related, but I'm noticing the opposite, that there is no diff when there should be. I'll dig into that and see if fixing that will fix your issue as well.

**Comment by ari-becker** [comment]
Hi @megan07 ,

The `secondary.example.com` is a [user alias domain](https://apps.google.com/supportwidget/articlehome?article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F7502379&assistant_event=welcome&assistant_id=!PzG6dMGRyYTUo6TlVeM9eD60ASX8v_wDkyDjz6HgGR4%3D&product_context=7502379&product_name=UnuFlow&trigger_context=a), where Google Workspace automatically adds an email account at the user alias domain for each user in Google Workspace. Since the user emails are added automatically as part of the user alias domain addition, the additional user emails cannot be deleted. In the Google Admin UX, they are part of the `Alternate email addresses (email alias)`, but are hidden under `Show all alternate emails`. If you show "all" the `alternate emails`, you see that they are greyed out and cannot be altered.
![image](https://user-images.githubusercontent.com/1388505/133827722-a666cf18-21bf-446c-b406-14df733f456c.png)

I agree that this is probably a diff suppression error - as these email addresses aren't really additionally defined email addresses per user, I don't see the value in needing to define an `email` per user just to align with the API response.

**Comment by megan07** [comment]
@ari-becker got it! Thank you! I think I'm going to suppress diffs against anything in the state without a `type`, does that sound accurate to you?

**Comment by ari-becker** [comment]
@megan07 yes, I think that sounds accurate. There's an edge case where Google adds additional user domain emails for user aliases as well, i.e. if the primary email is `foo@example.com` and there's a user alias domain `secondary.example.com`, then if the user is granted the alias `bar@example.com`, Google will add the email `bar@secondary.example.com` as well. However, in any event the `users.get` API call does not return a `type` for any of these emails, so it seems covered.
