### ISSUE TITLE
googleworkspace_group_members can not handle exististing users in group

### ISSUE THREAD

**Issue by mark-00** [hashicorp/terraform-provider-googleworkspace#192]
### Terraform Version
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/googleworkspace v0.5.0

### Affected Resource(s)
googleworkspace_group_members

### Terraform Configuration Files
```hcl
data "googleworkspace_group" "testgroup" {
  email = "test@test.com"
}

resource "googleworkspace_group_members" "add" {
  group_id = data.googleworkspace_group.testgroup.id
  members {
    email = "existing.member@test.com"
  }
}
```

### Expected Behavior
Since googleworkspace_group_members is authorative if an existing member is specified in a member block this shouldn't be a problem 

### Actual Behavior
Error is thrown

│ Error: googleapi: Error 409: Member already exists., duplicate
│ 
│   with googleworkspace_group_members.add,
│   on main.tf line 35, in resource "googleworkspace_group_members" "add":
│   35: resource "googleworkspace_group_members" "add" {
│ 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a workspace group
2.  add a user
3. `terraform apply` with code to add the same user as under step 2

**Comment by megan07** [comment]
@mark-00 I'm sorry! I'm going to have to revert the fix I put in for this issue, I didn't consider the obvious of if a user accidentally added the same member twice with 2 different roles, terraform won't know what to do with that. It's best to see the error and remove the duplicate member.

Let me know if you have further questions!

**Comment by gabor-farkas** [comment]
I also had this problem when I wanted to start managing the members of an already existing group.

I didn't check, does `import` work for that case?

**Comment by megan07** [comment]
Sorry for the delay @gabor-farkas, I missed this before. `import` should work, if you're seeing an issue with `import` feel free to open a new issue! Thanks!
