### ISSUE TITLE
Bug in googleworkspace_group_member

### ISSUE THREAD

**Issue by ozayss** [hashicorp/terraform-provider-googleworkspace#226]
Hello!

Great provider, but unfortunate I faced bug.
Could you please help me with this?

### Terraform Version
Terraform v1.0.11
registry.terraform.io/hashicorp/googleworkspace v0.5.2

### Affected Resource(s)
- googleworkspace_group_member

### Terraform Configuration Files
```hcl
resource "googleworkspace_group_member" "managers" {
  for_each = local.groups_managers
  group_id = googleworkspace_group.group[each.value.group].id
  email    = each.value.email

  role       = "MANAGER"
  depends_on = [googleworkspace_group_settings.group-settings]
}
```

### Debug Output
https://gist.github.com/ozayss/11f35e67b95e19189a57d8b9d2369754

### Panic Output
https://gist.github.com/ozayss/fb4b2293b52f533fc93b0a1c2a2a5a24

### Expected Behavior
Member is added to the group

### Actual Behavior
Sometime during creation error "404 Resource not found" appears, but members are added.
After that terraform shows error:
```
Stack trace from the terraform-provider-googleworkspace_v0.5.2_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xe96102]

goroutine 39 [running]:
github.com/hashicorp/terraform-provider-googleworkspace/internal/provider.resourceGroupMemberCreate(0x12e5b78, 0xc000485140, 0xc000643280, 0x1043ce0, 0xc000642480, 0xc000254370, 0xacedca, 0xc000080c80)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-googleworkspace/internal/provider/resource_group_member.go:156 +0x662

```
It can be fixed by removing problem members from group manually

**Comment by ozayss** [comment]
https://gist.github.com/ozayss/7bb2d1a006a99d565999e3f149551342

Crash log for 404 error, looks like it can't confirm resource after creation.

**Comment by megan07** [comment]
Hi @ozayss! I'm so sorry you've run into this. The good news is, this is actually a [duplicate](https://github.com/hashicorp/terraform-provider-googleworkspace/issues/216) and has already been fixed! It will be out in the next release. Thanks for your patience!
