### ISSUE TITLE
Feature Request: Add user to domain permissions in Google Domains

### ISSUE THREAD

**Issue by enchorb** [hashicorp/terraform-provider-googleworkspace#237]
Having the ability to add an email/user in Google Workspaces Domains (https://domains.google.com/) would be very useful 

ie, Currently when doing domain mapping with an impersonated Terraform account, for instance, mapping a custom domain to a Cloud Run instance it will give you an error until you manually go to google.com/webmasters/verification/home or Google Domains and add the Terraform service account.

**Comment by megan07** [comment]
Hi @enchorb! Thanks for the suggestion! I have been poking around here and haven't found an API that does this. Are you aware of one? I might be missing it.
Thanks!
