### ISSUE TITLE
We would like to contribute code

### ISSUE THREAD

**Issue by sv-cheats-1** [hashicorp/terraform-provider-googleworkspace#247]
Hello, are you willing to accept contributions to this? If so, is there any functionality in particular missing from the workspace provider that would assist with automation of Google Workspace deployment? Currently it seems like engineers spend significant amount of time configuring things manually and we here at Devoteam UK would be happy to help with solving that.
 
@megan07

**Comment by megan07** [comment]
Hi @sv-cheats-1!

Thanks so much for reaching out! We are always excited for help!

If you're looking for a place to start you can begin by reading our [Contribution Guide](https://github.com/hashicorp/terraform-provider-googleworkspace/blob/main/.github/CONTRIBUTING.md) and [Community Guidelines](https://www.hashicorp.com/community-guidelines). Then head on over to the [issues page](https://github.com/hashicorp/terraform-provider-googleworkspace/issues) and grab an issue you'd like to work on!

If there are features/bugs that you're aware of that aren't already tracked by the open issues, feel free to open an issue and assign yourself if you'd like!

Thanks for the interest!
