### ISSUE TITLE
Error 403: Request had insufficient authentication scopes.

### ISSUE THREAD

**Issue by dsiebel** [hashicorp/terraform-provider-googleworkspace#259]
### Preface

This might be more of a "request for comment/clarification" than an actual bug.  
What we are currently observing is the following:

We can plan and apply changes just fine from a GKE cluster with a Service Account using Workload Identity, but when we try to run import/plan/apply locally, using our personal users it fails with the error described below.
The Service Account has role `Groups Admin`, while the personal accounts we were testing with have `SuperAdmin` role in Google Workspace.

We were already in contact with Google (Workspace) Support several times and got nowhere.
They are not officially supporting Terraform and always suggest to "reach out to terraform".

So here it goes:

### Terraform Version

 1.1.5

### Affected Resource(s)

- `googleworkspace_group`

subsequently:

- `googleworkspace_group_settings`
- `googleworkspace_group_members`

### Terraform Configuration Files

```hcl
provider "googleworkspace" {
  customer_id = "XXXXXXX"
  // using all the scopes out of pure desperation
  oauth_scopes = [
    "https://www.googleapis.com/auth/apps.groups.settings",
    "https://www.googleapis.com/auth/chrome.management.policy",
    "https://www.googleapis.com/auth/admin.directory.user",
    "https://www.googleapis.com/auth/cloud-platform",
	"https://www.googleapis.com/auth/iam",
    "https://www.googleapis.com/auth/admin.directory.userschema",
    "https://www.googleapis.com/auth/gmail.settings.sharing",
    "https://www.googleapis.com/auth/gmail.settings.basic",
    "https://www.googleapis.com/auth/admin.directory.customer",
    "https://www.googleapis.com/auth/admin.directory.domain",
    "https://www.googleapis.com/auth/admin.directory.group",
    "https://www.googleapis.com/auth/admin.directory.orgunit",
    "https://www.googleapis.com/auth/admin.directory.rolemanagement",
  ]
}

resource "googleworkspace_group" "group" {
  description = "test group"
  email       = "supcase-29356487@trivago.com"
}
```

### Debug Output

https://gist.github.com/dsiebel/5950f119bff40c11d9c27f737c964fb8

### Panic Output

N/A

### Expected Behavior

A new group to be created in Google Workspace.

### Actual Behavior

`terraform plan` shows the group will be created. On `terraform apply` the API response is:
>  Error 403: Request had insufficient authentication scopes.

Also when running plan after a previous apply (see preface), the plan already fails when trying to read an existing group.

### Steps to Reproduce

`terraform apply`

### Important Factoids

We are running terraform via Atlantis in a GKE cluster which uses a Service Account via Workload Identity to apply the changes. This Service Account has "Groups Admin" role in Google Workspace.
**This work perfectly fine**, however when trying to plan/apply locally, using our local users (`SuperAdmin` on Google Workspace), the aforementioned error occurs.

### References

N/A

**Comment by megan07** [comment]
Hi @dsiebel ! I'm sorry that you're running into this issue, I'd like to help out here as best I can. It seems to me it might be a scopes issue. So, the scopes that you grant to your service account needs to match, or be a superset, of the `oauth_scopes` granted to the provider. So, I see you listed all of those scopes out of desperation - but that may either be part of the issue, or hiding a different issue, so what I first want to have you do is see if you can limit the `oauth_scopes` to just `"https://www.googleapis.com/auth/admin.directory.group"` and `"https://www.googleapis.com/auth/cloud-platform"` and double-check in the admin console that the `Oauth Scopes` granted to the service account match those same scopes, or that there are more in the admin console. Does that make sense? [See here.](https://developers.google.com/admin-sdk/directory/v1/guides/delegation#delegate_domain-wide_authority_to_your_service_account)

The other thing I want to check is that I see the service account being impersonated via workload identity is working correctly, are you using credentials from a different service account locally?

**Comment by megan07** [comment]
@dsiebel ahh! ok! Did you use the `--scopes` flag to specify the scopes when you logged in?
https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login

I think you'll want to list the same scopes there. Let me know if that helps! Thanks!

**Comment by dsiebel** [comment]
When I tried Google Login was telling me that the "App is blocked", so, naturally, I assumed that this was something I wasn't supposed to do.
Turns out we needed to trust the "Google Auth Library" / gcloud SDK to access all Google Services and I was able to expand the scopes on my ADC login.

Thanks a bunch @megan07 ! 🙂

**Comment by megan07** [comment]
Thanks for the extra information @dsiebel ! I'm happy it's working!

**Comment by gmile** [comment]
> Turns out we needed to trust the "Google Auth Library" / gcloud SDK to access all Google Services and I was able to expand the scopes on my ADC login.

@dsiebel would you be so kind as to share how exactly you enable "trust" Google Auth Library / gcloud SDK?

I'm failing to generate application default credentials using `gcloud`. After running this, I am basically hitting an error when trying to consent to authorise the app in a browser:

```
gcloud auth application-default login --scopes openid,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/admin.directory.user,https://www.googleapis.com/auth/admin.directory.group,https://www.googleapis.com/auth/apps.groups.settings,https://www.googleapis.com/auth/iam
```

...after attempting to consent in browser:

> **This app is blocked**. This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

**Comment by dsiebel** [comment]
> **Upd**. Found it. One should go to [admin.google.com/ac/owl/list?tab=configuredApps](https://admin.google.com/ac/owl/list?tab=configuredApps), and whitelist the app there using `gcloud`'s client_id, the value for `client_id` can be seen in the `https://accounts.google.com/o/oauth2/auth?...` URL during OAuth2 consent.

Did you manage to solve it with that?
I ran into some other issues but didn't have the time yet to further look into it.

**Comment by dsiebel** [comment]
I found [this medium article](https://medium.com/google-cloud/google-oauth-credential-going-deeper-the-hard-way-f403cf3edf9d) researching the project number. I have been meaning to give it a try.

**Comment by dsiebel** [comment]
I managed to get it working using service account impersonation all the way.
Using one `google` provider to get the access token and configure another `google` provider and the `googleworkspace` provider via `access_token` argument:
```tf
data "google_service_account_access_token" "impersonatee" {
  target_service_account = local.service_account
  scopes = [
    "https://www.googleapis.com/auth/admin.directory.user",
    "https://www.googleapis.com/auth/admin.directory.group",
    "https://www.googleapis.com/auth/apps.groups.settings",
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/iam",
  ]
}
provider "googleworkspace" {
  customer_id     = "<redacted>"
  access_token    = data.google_service_account_access_token.impersonatee.access_token
  service_account = local.service_account
  oauth_scopes = [
    "https://www.googleapis.com/auth/admin.directory.user",
    "https://www.googleapis.com/auth/admin.directory.group",
    "https://www.googleapis.com/auth/apps.groups.settings",
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/iam",
  ]
}

[...]
```
Important to note, that the access scopes need to match, as also mentioned in this issue.

**Comment by gmile** [comment]
> I am guessing that's what https://github.com/hashicorp/terraform-provider-googleworkspace/issues/264 is about?

@dsiebel precisely, yes.

> I managed to get it working using service account impersonation all the way.

It appears that service account's access token is being part of Terraform state? I was looking for ways to specifically avoid storing any service account credentials as part of .tf state 🤔

For context, we are a small team, each of us runs terraform locally on our computers. Ideally, we don't want to infiltrate the .tf state with the access tokens that allow controlling users / groups at the organisation level, as I find it to be quite risky. Ideally, in our situation, all control would be done using local developer credentials, found on the computer.

**Comment by gabor-farkas** [comment]
@gmile it's also possible to specify impersonation with an environment variable, https://cloud.google.com/blog/topics/developers-practitioners/using-google-cloud-service-account-impersonation-your-terraform-code - afaik that approach avoids storing tokens in the state.

(Otherwise, the Terraform state storage can be set up to be accessible only by people who have 'generateAccessToken' privileges anyway, and the token otherwise has a short expiration.)

**Comment by dsiebel** [comment]
Sorry, for the delay. My answers below.

> It appears that service account's access token is being part of Terraform state? I was looking for ways to specifically avoid storing any service account credentials as part of .tf state 🤔

No it is not. The access token is retrieved using a Terraform datasource. That is why the user interacting with the terraform state need to have `roles/iam.serviceAccountTokenCreator` on said service account.

EDIT: now that I wrote that I am suddently not sure whether the value of the data source will be persisted in the remote state (GCS) or not 🤔
