### ISSUE TITLE
'General feedback' form from readme - no permissions to fill the form

### ISSUE THREAD

**Issue by mwieczorek** [hashicorp/terraform-provider-googleworkspace#299]
README.md has 'General feedback' section with a link to a form.
When I access the page, I see a message that I don't have permission to access the form, and the form is available only to users from form's owner org.

**Comment by megan07** [comment]
@mwieczorek - oh no, that's no good. sorry about that!
@tejavar, would you mind taking a look?
thanks for letting us know!

**Comment by megan07** [comment]
@mwieczorek - I think this is fixed now! Would you please double-check, and if it is, we can close this issue. Thanks so much!
