### ISSUE TITLE
Feature Request: Group Subject Prefix

### ISSUE THREAD

**Issue by enchorb** [hashicorp/terraform-provider-googleworkspace#309]
Does Google expose the subject prefix for a group in the `googleworkspace_group_settings` or `googleworkspace_group`, this is the only part of Workspace groups that we still have to do manually

**Comment by SarahFrench** [comment]
Hi @enchorb, sadly subject prefix isn't managed by the Group Settings API, so this feature can't be added until that changes. [This page](https://developers.google.com/admin-sdk/groups-settings/manage#retrieving-settings-for-a-group) shows the fields that the API makes accessible.

I'd recommend going to these IssueTracker pages, where people are requesting this feature to be added to the API, and star the issue & click the `+1` button at the top to support the feature request and show interest:
- [IssueTracker: Add support of Subject Prefix into Group Settings API](https://issuetracker.google.com/issues/36758316)
- [IssueTracker: Allow ANY groups settings to be updated via the API](https://issuetracker.google.com/issues/36759145)

**Comment by enchorb** [comment]
@SarahFrench Thanks for finding that, I added a vote for it! Will close this out for now
