### ISSUE TITLE
Link to provider docs in readme is broken

### ISSUE THREAD

**Issue by discentem** [hashicorp/terraform-provider-googleworkspace#78]
### Expected Behavior
The link in this section should work. 

https://github.com/hashicorp/terraform-provider-googleworkspace#using-the-provider 

### Actual Behavior

https://registry.terraform.io/docs/providers/googleworkspace leads to a 404.

**Comment by tejavar** [comment]
Hi ! 

The Google Workspace repo is a technical preview and hasn't officially launched. The link will be active when we officially launch the provider.
