### ISSUE TITLE
Upgrade guide from DeviaVir/gsuite

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-googleworkspace#94]
### Expected Behavior
https://registry.terraform.io/providers/hashicorp/googleworkspace/latest/docs should contain an upgrade guide with instructions on how to upgrade from `DeviaVir/gsuite` now that https://github.com/DeviaVir/terraform-provider-gsuite is deprecated and tells people to migrate to this new provider.

### Actual Behavior
Unable to find any such instructions or tips on the old or new provider pages.

**Comment by joe-a-t** [comment]
Hey @megan07, thanks a lot for the quick response. I noticed [group_settings#who_can_approve_members](https://registry.terraform.io/providers/DeviaVir/gsuite/latest/docs/resources/group_settings#who_can_approve_members) (which was marked as deprecated in DeviaVir/gsuite docs but not emitting warnings) is not present in this new provider so it would be great if that could be noted in https://github.com/hashicorp/terraform-provider-googleworkspace/blob/main/docs/upgrade_guide.md#resource-googleworkspace_group_settings

**Comment by megan07** [comment]
According to Google's [documentation](https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups#json), this field is not yet deprecated, so I'm assuming the functionality hasn't been merged into `whoCanModerateMembers` yet. As such, I think this is a bug and needs to still be a part of the resource. I'll open a new issue and add that in. Thanks!

**Comment by joe-a-t** [comment]
Hey @megan07, can we actually reopen this? I tried migrating following the upgrade guide which does a great job covering the differences, but it looks like there is a gap in terms of how you adjust the Terraform state for existing resources. Trying to run `terraform state mv` results in 
```
│ Error: Invalid state move request
│ 
│ Cannot move gsuite_group.group to
│ googleworkspace_group.group: resource types
│ don't match.
```
We cannot destroy and re-create all of the resources so is there a migration path that allows us to avoid `terraform import` with googleworkspace and `terraform state rm` with gsuite for each individual resource?

**Comment by appilon** [comment]
@joe-a-t Unfortunately it's a common painpoint of Terraform (bulk import) but essentially yes, you will need to script this process

**Comment by joe-a-t** [comment]
Ok, so HashiCorp/Google has no plans to assist in that process by publishing a script or something to do the relevant state manipulation and is instead expecting that all users of the gsuite provider will write their own script to migrate?

**Comment by megan07** [comment]
Hi @joe-a-t , thanks for the request and the feedback. I'm going to keep this issue closed as I'd like the upgrade guide to go out with the next release as is. However, I appreciate the request and feedback here, and will open another issue to discuss at our next triage meeting. I'm thinking I'd like to explore an idea of a tool rather than documentation.

We had discussed a similar idea prior to launch, however, decided to defer it until we were sure people would want to use this provider in-lieu of the gsuite provider. So far, you're the only person to ask for this functionality, and we appreciate your engagement. I will update the status on the new issue after we have an opportunity to triage this request as a group.

**Comment by joe-a-t** [comment]
Thanks a lot. It might be nice to just add a link to that issue to the upgrade guide as a placeholder so that people can better decide if they want to invest the time in investigating an upgrade now or wait for that sort of tool.
